# Stage 1: Compile and Build angular codebase

FROM node:alpine as builder

RUN mkdir -p /src

WORKDIR /src

ADD src/package.json /src/package.json

RUN npm install

COPY src/ /src/

RUN npm run build --prod

# Stage 2: Serve app with nginx server

FROM nginx:alpine

COPY --from=builder /src/dist/angular-frontend /usr/share/nginx/html

EXPOSE 80